### ISSUE TITLE
Link for "associated API" on About pages

### ISSUE THREAD

**Issue by hhopkins77** [sfg-taxonpages/issues#27]
Could someone get me the text that goes with the above links on each of my SFs? I think they can go live without it, but it is the last thing that is missing. Thank you!

**Comment by mjy** [comment]
The base API is `https://sfg-taxonworks.org/api/v1` so in Markdown to link that text you might do this:

```
[associated API](https://sfg-taxonworks.org/api/v1)
```

**Comment by hhopkins77** [comment]
Just confirming Matt that I use that text on all About pages....there is no distinction in the text from file to file?

**Comment by mjy** [comment]
Right.  The base API is the same for all.  Projects are differentiated by a project_token when callers make a call to a specific "resource" (like https://sfg.taxonworks.org/api/v1/taxon_names?project_token=123abc).  

We could add text with "instructions" to using the api that links to api.taxonworks.org

**Comment by hhopkins77** [comment]
Triple checking this is the link to go with this text on the About page, which seems to indicate COL API, yes/no? (Apologies for endless queries. I don't think I was clear in my original issue.)

Core taxonomic data are exported to and available at the [Catalogue of Life] and its [associated API].

**Comment by mjy** [comment]
Oh, yah, that's different :)

**Comment by mjy** [comment]
@gdower can you help @hhopkins77 track down COL related links where available?

**Comment by gdower** [comment]
@hhopkins77, there's lots of potential options for linking to the ChecklistBank/COL API. For starters, I'd recommend linking to the API documentation: 

http://api.checklistbank.org

The corresponding link to what you have on your about page in the COL Portal would be:

https://api.checklistbank.org/dataset/3LR/taxon/TM

Linking to the classification tree:

https://api.checklistbank.org/dataset/3LR/tree/TM

If you want to link specifically to the Cockroach dataset in ChecklistBank instead of COL:

https://api.checklistbank.org/dataset/1051/taxon/54406
https://api.checklistbank.org/dataset/1051/tree/54406

@mjy, I think the 54406 ID is pseudo-stable now that it is imported into prod? I supposed those IDs could still change if we did a major migration for some reason, which would break that link in the future.

I'm aiming to also add links from COL back to each taxon page in the TaxonPage projects, but need to finish the COLDP dataset export profile feature in order to be able to store the TaxonPage base URL in export settings.

**Comment by hhopkins77** [comment]
Thank you @gdower. @mjy should I go with the first one above on all species files? Let me know when you have time, not urgent.

**Comment by gdower** [comment]
It's up to you, but maybe it would be best to link to the API documentation and possibly the root taxon for each project like below?

https://api.checklistbank.org/dataset/3LR/taxon/TM

**Comment by hhopkins77** [comment]
I agree that is better, and that text seems to be for Blattodea. For Embioptera would I use:

https://api.checklistbank.org/dataset/3LR/taxon/8MP8H?

**Comment by hhopkins77** [comment]
Done.

**Comment by gdower** [comment]
> I agree that is better, and that text seems to be for Blattodea. For Embioptera would I use:
> 
> https://api.checklistbank.org/dataset/3LR/taxon/8MP8H?

Yes, and if you want to do a quick name usage search of COL via the API for the other taxon IDs, it would be:

https://api.checklistbank.org/dataset/3LR/nameusage/search?q=Embioptera
